### ISSUE TITLE
Allow invoke to preserve call & context errors for retry until timeout

### ISSUE THREAD

**Issue by tritone** [googleapis/gax-go#158] opened 2021-12-16 20:11 UTC
Currently if `Invoke` is called and the request is retried until a timeout, it will return a context error only. The underlying error from the service will be lost.

We can use error wrapping to preserve both errors. See googleapis/google-cloud-go#4797 for an example.

**Comment by codyoss** [comment] 2022-12-21 19:40
Closing as a dupe of https://github.com/googleapis/gax-go/issues/235

**Closed** 2022-12-21 19:40 UTC
Labels: type: feature request, priority: p3
